name: Fedora 41

env:
  FEDORA: 41
  GPG_KEY_ID: 56C464BAAC421453

on:
  push:
    tags:
      - 'fedora-41-*'

  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-latest
    steps:
      - name: Maximize disk space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 5120
          remove-dotnet: true
          remove-android: true
          remove-docker-images: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize containers
        run: |
          bash ./.github/scripts/container/create.sh \
            registry.fedoraproject.org/fedora:${{ env.FEDORA }}

      - name: Install build dependencies
        run: |
          bash ./.github/scripts/container/exec.sh \
            -- \
            bash ./.github/scripts/package/fedora.sh setup-builddeps

      - name: Setup secureboot certificate
        env:
          SB_KEY: ${{ secrets.SURFACE_SB_KEY }}
        run: |
          bash ./.github/scripts/container/exec.sh \
            -e SB_KEY \
            -- \
            bash ./.github/scripts/package/fedora.sh setup-secureboot

      - name: Build packages
        run: |
          bash ./.github/scripts/container/exec.sh \
            -- \
            bash ./.github/scripts/package/fedora.sh build-packages

      - name: Sign packages
        env:
          GPG_KEY: ${{ secrets.LINUX_SURFACE_GPG_KEY }}
        run: |
          bash ./.github/scripts/container/exec.sh \
            -e GPG_KEY \
            -e GPG_KEY_ID \
            -- \
            bash ./.github/scripts/package/fedora.sh sign-packages

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fedora-${{ env.FEDORA }}-latest
          path: pkg/fedora/kernel-surface/out/x86_64

